name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t whitechapel5991/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true whitechapel5991/react-test npm test

      - run: docker build -t whitechapel5991/multi-client-up ./client
      - run: docker build -t whitechapel5991/multi-nginx-up ./nginx
      - run: docker build -t whitechapel5991/multi-server-up ./server
      - run: docker build -t whitechapel5991/multi-worker-up ./worker
 
      - run: docker push whitechapel5991/multi-client-up
      - run: docker push whitechapel5991/multi-nginx-up
      - run: docker push whitechapel5991/multi-server-up
      - run: docker push whitechapel5991/multi-worker-up
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'