name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t whitechapel5991/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true whitechapel5991/react-test npm test

      - run: docker build -t whitechapel5991/multi-client-10-14 ./client
      - run: docker build -t whitechapel5991/multi-nginx-10-14 ./nginx
      - run: docker build -t whitechapel5991/multi-server-10-14 ./server
      - run: docker build -t whitechapel5991/multi-worker-10-14 ./worker
 
      - run: docker push whitechapel5991/multi-client-10-14
      - run: docker push whitechapel5991/multi-nginx-10-14
      - run: docker push whitechapel5991/multi-server-10-14
      - run: docker push whitechapel5991/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'